"""L3: Per-ticker markdown research reports."""
import logging
from datetime import datetime
from pathlib import Path

import yaml

from analysis.combined_score import get_all_ai_results

logger = logging.getLogger(__name__)
ROOT = Path(__file__).parent.parent
_cfg = yaml.safe_load((ROOT / "config.yaml").read_text())


def _fmt(val, fmt=".2f", default="N/A"):
    try:
        if val is None or val != val:
            return default
        return f"{val:{fmt}}"
    except Exception:
        return default


def generate_report(ticker: str, row: dict) -> str:
    """Generate a markdown research report for a ticker."""
    ai = get_all_ai_results(ticker)
    earnings = ai.get("earnings") or {}
    filings = ai.get("filings") or {}
    risks = ai.get("risks") or {}
    insiders = ai.get("insiders") or {}

    signal = row.get("signal", "NEUTRAL")
    signal_emoji = {"LONG": "🟢", "SHORT": "🔴", "NEUTRAL": "⚪"}.get(signal, "")

    report = f"""# {signal_emoji} {ticker} — {row.get('company_name', ticker)}
**Signal:** {signal} | **Sector:** {row.get('sector', 'N/A')}
**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}

---

## Quantitative Scores (0-100, sector-relative)

| Factor | Score |
|--------|-------|
| **Composite** | **{_fmt(row.get('composite'), '.1f')}** |
| Momentum | {_fmt(row.get('momentum'), '.1f')} |
| Quality | {_fmt(row.get('quality'), '.1f')} |
| Value | {_fmt(row.get('value'), '.1f')} |
| Growth | {_fmt(row.get('growth'), '.1f')} |
| Estimate Revisions | {_fmt(row.get('estimate_revisions'), '.1f')} |
| Insider Activity | {_fmt(row.get('insider_activity'), '.1f')} |
| Short Interest | {_fmt(row.get('short_interest'), '.1f')} |
| Institutional Flow | {_fmt(row.get('institutional_flow'), '.1f')} |

---

## Claude AI Analysis

### Earnings Call
{f"**Score: {earnings.get('management_confidence')}/10 confidence | {earnings.get('revenue_guidance')}/10 guidance**" if earnings else "_No transcript available_"}
{f"> {earnings.get('one_line_summary', '')}" if earnings else ""}
{f"- **Bull:** {earnings.get('bull_case', '')}" if earnings else ""}
{f"- **Bear:** {earnings.get('bear_case', '')}" if earnings else ""}

### Filing Quality
{f"**Earnings Quality: {filings.get('earnings_quality_score')}/10 | Balance Sheet: {filings.get('balance_sheet_score')}/10 | Risk: {filings.get('risk_level')}**" if filings else "_No filing analysis_"}
{f"> {filings.get('one_line_summary', '')}" if filings else ""}
{chr(10).join(f"- 🚩 {flag}" for flag in filings.get('red_flags', [])) if filings else ""}
{chr(10).join(f"- ✅ {flag}" for flag in filings.get('green_flags', [])) if filings else ""}

### Risk Factors
{f"**Risk Severity: {risks.get('risk_severity')} | Boilerplate: {risks.get('boilerplate_percentage')}%**" if risks else "_No 10-K analysis_"}
{f"> {risks.get('one_line_summary', '')}" if risks else ""}
{chr(10).join(f"- {r}" for r in risks.get('material_risks', [])) if risks else ""}

### Insider Activity
{f"**Signal: {insiders.get('signal_strength')} ({insiders.get('confidence')} confidence)**" if insiders else "_No insider transactions_"}
{f"> {insiders.get('one_line_summary', '')}" if insiders else ""}
{f"{insiders.get('reasoning', '')}" if insiders else ""}

---

*Report generated by Meridian Capital Partners JARVIS system*
"""
    return report


def save_reports(scored_df, output_dir: Path | None = None):
    """Generate and save markdown reports for all LONG/SHORT candidates."""
    if output_dir is None:
        ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        output_dir = ROOT / "output" / f"reports_{ts}"
    output_dir.mkdir(parents=True, exist_ok=True)

    candidates = scored_df[scored_df["signal"].isin(["LONG", "SHORT"])]
    saved = 0
    for ticker, row in candidates.iterrows():
        try:
            report = generate_report(ticker, row.to_dict())
            path = output_dir / f"{ticker}.md"
            path.write_text(report)
            saved += 1
            logger.info("Report saved: %s", path)
        except Exception as e:
            logger.error("Report error %s: %s", ticker, e)

    logger.info("Reports saved: %d / %d candidates", saved, len(candidates))
    return output_dir
